### ISSUE TITLE
URI validity check?

### ISSUE THREAD

**Issue by kaur2k** [medialize/URI.js#140]
Any thoughts about including URI validity/correctness check? To determine if given string is an URI or not.

**Comment by cowwoc** [comment]
I just wanted to throw some more oil into the fire...

If you take a look at http://docs.oracle.com/javase/8/docs/api/java/net/URI.html#URI-java.lang.String- you will see that they throw an error if a URI does not parse according to http://www.ietf.org/rfc/rfc2396.txt

If you take a look at Appendix A, it seems the major difference between your interpretations is that Java and RFC2396 require all URI components to be present (e.g. scheme, // separator) whereas this library assumes that if these components are missing then what we have is a path without a protocol or scheme.

I personally lean towards Java's interpretation because RFC2396 is, in fact, the standard definition of a URI. Would you care to revisit this issue in light of this fact?

**Comment by cowwoc** [comment]
In http://medialize.github.io/URI.js/about-uris.html you write:

> URIs don't have to contain scheme and authority

but judging by the RFC, this isn't strictly correct. The only time it seems to be legal to omit a scheme is for network-relative references ... and those are required to start with `//`.

So a string that does not begin with `//` and does not contain a scheme should be invalid.

**Comment by cowwoc** [comment]
Nevermind. Looking at https://tools.ietf.org/html/rfc3986#section-4.1 I see now that a scheme is only required for absolute URIs. Relative URIs can be equal to `relative-part` which looks like they can contain anything. So yeah, I guess you're right. Sorry for the false alarm :)
