### ISSUE TITLE
.equals(undefined)

### ISSUE THREAD

**Issue by eakron** [medialize/URI.js#189]
If I am on the page "http://local.local" and run `URI('http://local.local').equals(undefined)` I get `true`. Comparing a different URL to undefined gives false. As far as I can tell, this only happens if the argument to `URI` is the current page URL.

I assume this is so that `URI()` is a shortcut for current URL. This can be differentiated by looking at `arguments`. Will make a pull request.

Using version 1.14.1.

**Comment by rodneyrehm** [comment]
that's because `.equal()` runs the argument through `URI()`, making the following all do the same thing: 

```js
URI(location.href).equals(URI(location.href)) === true;
URI(location.href).equals(URI()) === true;
URI(location.href).equals() === true;

URI().equals(URI(location.href)) === true;
URI().equals(URI()) === true;
URI().equals() === true;
```

I don't consider this a bug. Maybe the documentation could be more clear about it…

**Comment by eakron** [comment]
While all of those make sense
`````
URI(undefined).equals(URI()) === true
`````
doesn't really. It is very easy to make mistakes by inputting something you think is a value (but is really undefined) to URI. This is not a logical behavior. A possible solution would be adding
`````
      if (arguments.length === 1) {
        throw new TypeError('undefined is not a valid argument for URI');
      }
`````
to line 43. But obviously it is your call!

**Comment by rodneyrehm** [comment]
(I took the liberty of fixing your code examples and make [line 43](https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L43) be 100x more useful by linking it to the mentioned line…)

The constructor takes 2 arguments, so you'd likely check `if (arguments.length)` instead, agree?
PR welcome, don't forget the tests :)

> But obviously it is your call!

Actually it's the community's, as your suggested change introduces a (tiny) backward compatibility break (which I assume most people wouldn't run into):

```js
// currently equivalent
URI(undefined);
URI(location.href);
```

But I guess that's fine, considering that you suggested throwing an error instead of silently using the empty string.

**Comment by rodneyrehm** [comment]
@eakron do you want to send a PR to fix this issue?

**Comment by eakron** [comment]
Pull request: https://github.com/medialize/URI.js/pull/196
