### ISSUE TITLE
rename in package managers from `URIjs` to `urijs`

### ISSUE THREAD

**Issue by rodneyrehm** [medialize/URI.js#206]
The people over at npm are a funny bunch. I can't update [URIjs](https://www.npmjs.com/package/URIjs) on npm because »Invalid name: "URIjs"« (npm v2.7.5). Others seem to have the same problem [npm#7195](https://github.com/npm/npm/issues/7195).

A possible resolution is to rename the project from `URIjs` to `urijs`. [`uri.js`](https://www.npmjs.com/package/uri.js) is taken by some incomplete, unmaintained and not very popular project. [`uri-js`](https://www.npmjs.com/package/uri-js) is taken by a project that has slightly more downloads on npm (and way less stars on github - I guess that says everything you need to know about github stars…).

Anyway, I didn't want to just rename the thing before giving the chance to object (and propose another solution)

**Comment by barneycarroll** [comment]
That's really weird. Presumably you won't even be able to let NPM users know the  package registered as URIjs is dead. But then you'd think the guys at NPM would want resolve this rather than let the registry fill up with dead and duplicate packages — and surely it'd be better to let the package fall behind a few releases (no major bug fixes since last successful push, right?) until NPM sort out the underlying problem rather than have to deal with the fallout of people complaining about 'URIjs' being out of date for all eternity…?

**Comment by rodneyrehm** [comment]
I agree that there is probably no immediate action required. 1.5.0 is on npm. The thing that will not work (and is fixed by 1.15.1) is `URI()` as opposed to `new UR()` and `URI(location.href)`, which are both doing the same thing.

I pushed `1.15.0` 5 days ago and updated npm in the meantime. Downgrading npm all the way down to `2.0.0` didn't help, so I assume this is a server side problem.

**Comment by barneycarroll** [comment]
I think it's safe to say that bug fix isn't crucial — anybody who's come to rely on URIjs over the years will have dealt with that almost immediately and figured out their own way of working with the API as it was: it's not as if it's a dangerous corner case that breaks all sorts of stuff, or a bug caused by recent API change…

**Comment by barneycarroll** [comment]
BTW, I'd strongly urge to let NPM fix their mess rather than try and mitigate this with duplicate entries for URIjs — it feels all sorts of wrong and if you imply you're taking responsibility for this problem it leaves the door open for all sorts of user confusion coming knocking on your door further on down the line…

**Comment by rodneyrehm** [comment]
npm [introduced scopes](http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages) so I guess we'll make URI.js available as `@medialize/uri.js` now? I wonder what other package managers think of this notation…

**Comment by ooxi** [comment]
@rodneyrehm I read the blog post you quoted but I don't quite get it. Does this mean the old npm package is dead and will never receive updates? Or will my `package.json` files break since the package was moved from `URIjs` to `@medialize/uri.js`?

**Comment by rodneyrehm** [comment]
> Does this mean the old npm package is dead and will never receive updates?

apparently not:

```js
➜  git checkout v1.15.1
HEAD is now at 42a16eb... chore(build): updating distributables to 1.15.1

➜  npm publish
+ URIjs@1.15.1
```

> since the package was moved 

The package wasn't moved yet. I consider this the measure of last resort. I will not rename it unless I have to. But even if we were to rename the package, your existing projects wouldn't notice - the packages previously published to npm remain available - you just wouldn't get updates anymore…

---

closing since I was able to publish 1.15.1 just now

**Comment by rodneyrehm** [comment]
I have just renamed the package to `urijs` in npm (was `URIjs`) and bower (was `uri.js`).

new on npm: [urijs](https://www.npmjs.com/package/urijs)
old on npm [URIjs](https://www.npmjs.com/package/URIjs)

```
➜  bower search uri.js
Search results:

    uri.js git://github.com/medialize/URI.js.git
    URIjs git://github.com/medialize/URI.js.git
    urijs git://github.com/medialize/URI.js.git (<---)
```
