### ISSUE TITLE
Add decodeURI to expanding template string

### ISSUE THREAD

**Issue by DSIW** [medialize/URI.js#208]
I have the following example to demonstrate the problem:

```js
URI.expand("/path/{id}.js", {id: 1}).toString() // => /path/1.js

URI.expand("/path/%7Bid%7D.js", {id: 1}).toString() // exception

URI.expand(decodeURI("/path/%7Bid%7D.js"), {id: 1}).toString() // => /path/1.js
URI.expand(decodeURI("/path/{id}.js"), {id: 1}).toString() // => /path/1.js
```

I think it's better to add the `decodeURI` method to your `expand` method. There is no problem for already decoded strings.

What do you think?

**Comment by rodneyrehm** [comment]
> `URI.expand("/path/%7Bid%7D.js", {id: 1}).toString() // exception`

What's the exception look like? When I run your example I get the expected result: `"/path/%7Bid%7D.js"`

I don't think there's anything wrong here… simply decoding everything *would* introduce problems, because it would become impossible (ok, not impossible, more difficult) to have the literal value `%7Bid%7D` in the URL - someone may actually want that…

**Comment by DSIW** [comment]
Hi Rodney,
sorry, there was no exception but I expected the decoded uri. I agree with you and will close this issue!
