### ISSUE TITLE
.absoluteTo inappropriately decodes URL

### ISSUE THREAD

**Issue by bradleyayers** [medialize/URI.js#222]
There's a bug in `.absoluteTo` which causes the URL to be decoded, when it shouldn't.

    > (new URI("%26")).toString()
    "%26"
    > (new URI("%26")).absoluteTo("/").toString()
    "/&"

I would expect the behaviour to instead be:

    > (new URI("%26")).absoluteTo("/").toString()
    "/%26"

Interestingly this doesn't affect _all_ URL encoded reserved characters:

    (new URI("%27")).absoluteTo("/").toString()
    "/%27"
    (new URI("%28")).absoluteTo("/").toString()
    "/%28"

**Comment by rodneyrehm** [comment]
The "problem" is introduced by the call to `URI.recodePath()` via `.normalizePath()`. This is happening because `&` does not have to be pct-encoded in the path segment of a URI. You'd want the `&` escaped in the query component, but not in the path.

So far this is not a bug. What's the real problem you've encountered, maybe there's a different way to avoid this?

---

I see you're working for Atlassian. is URI.js used in any of their tools?

**Comment by bradleyayers** [comment]
Ah interesting!

The different pct-encoding requirements depending on _where_ in the URI the character is used is what was tripping me up. I was just using `encodeURIComponent(…)` which obviously doesn't have enough information about _where_ in the URI you're targeting, so it's more aggressive than necessary with pct-encoding.

Thanks for the details, I'll take a closer look at https://tools.ietf.org/html/rfc3986.

----

Atlassian is using URI.js in _at least_ JIRA (it's the product I'm currently working on), but I wouldn't be surprised if it was used in more places too.
