### ISSUE TITLE
[BUG] Bad port parsing when hash (#) is used in password part.

### ISSUE THREAD

**Issue by o5** [medialize/URI.js#228]
Step to repro in node.js

```js
var uri = require('URIjs')('rtsp://user:wbd%0#0NnWS+@1.2.3.4:88/videoSub');

//1
console.log(uri.port()); //prints `wbd%0` instead of `88`

//2
console.log(uri);
```

Second prints:
```
{ [String: 'rtsp://user:wbd%0/#0NnWS+@1.2.3.4:88/videoSub']
  _string: 'rtsp://user:wbd%0/#0NnWS+@1.2.3.4:88/videoSub',
  _parts:
   { protocol: 'rtsp',
     username: null,
     password: null,
     hostname: 'user',
     urn: null,
     port: 'wbd%0',
     path: '/',
     query: null,
     fragment: '0NnWS+@1.2.3.4:88/videoSub',
     duplicateQueryParameters: false,
     escapeQuerySpace: true },
  _deferred_build: false }
```
```
URIjs 1.15.1
Node v0.12.2
```

**Comment by o5** [comment]
question mark (?) has the same problem :/

**Comment by rodneyrehm** [comment]
This is not a bug. Try properly escaping your credentials and you'll succeed:

```js
URI('rtsp://1.2.3.4:88/videoSub').username('user').password('wbd%0/#0NnWS+').toString()
// rtsp://user:wbd%250%2F%230NnWS%2B@1.2.3.4:88/videoSub
```

Both `?` and `#` denote specific segments of the URL. In a way, they are the most relevant characters. *Anything* that follows the first `#` is considered the fragment (also known as "hash"). *Anything* that follows `?` and is not part if the fragment is considered the query string (also known as "search").

**Comment by o5** [comment]
Thank you for reply! Unfortunately, your answer doesn't solve my problem :-( . I've a URI string (entered by user) and I need to parse it.

**Comment by rodneyrehm** [comment]
I'm sorry, URI.js won't solve *this* problem for you. If you have power over the input form, you may want to show the user what you understood to lower the error rate. or possibly make username and password available as separate fields.

Otherwise you're stuck with *guessing* what the string really means. I'm pretty sure you can create some heuristics, but they're likely not going to hit the target 100% of time - that's why URI.js isn't even trying to do that.
