### ISSUE TITLE
RequireJS hits a 404 when minified file attempts to load "./URI"

### ISSUE THREAD

**Issue by viveleroi** [medialize/URI.js#254]
Installed via bower and configured RequireJS:

    paths: {
      urijs = '/dist/uri.js/URI.min'
    }

We have a build system that copies only `URI.min.js` to our deploy path.

However, once this js file has loaded, `RequireJS` hits a 404 trying to find:

`http://127.0.0.1:8080/URI.js?bust=1443743941152` 

I'm not sure what's causing this - I assume "URI" is a package defined within that same file, so I don't understand why require is going out and trying to find it.

Update: I've tried to reproduce this by cloning the repo and hitting a basic html file with requirejs. While I am able to get the file to load, the example on your README throws a "URI is not a function" error, and the object I'm given has properties `best` and `noConflict` - it seems to be giving me the IPv6 module...

https://pste.me/#/BdSlk

**Comment by rodneyrehm** [comment]
if you're using require, you may want to use the source files, not the minifed ones.

**Comment by viveleroi** [comment]
Unfortunately, that won't work for me and I'll have to find an alternative. I can't accept adding four new HTTP requests for a single library to work, plus spending time ensuring those additional files are all included in our deploy tasks to be properly minified.

**Comment by rodneyrehm** [comment]
> […] plus spending time ensuring those additional files are all included in our deploy tasks to be properly minified.

so you're using RequireJS, but not the [optimizer](http://requirejs.org/docs/optimization.html)?

**Comment by viveleroi** [comment]
We have a separate series of gulp tasks which prepare and minify our app for deployment. All of the vendor libraries we're using have minified distribution-ready files already, so we can use those directly. Since require loads files as we need them, and everything is self-contained already, we've never worried about having to concat other people's stuff.

**Comment by rodneyrehm** [comment]
At this moment URI.js is not available in a concatenated and minified version that is consumable by RequireJS. The assumption was that RequireJS users would be running the optimizer and prefer to integrate through that.

**Comment by viveleroi** [comment]
I'd suggest making that disclaimer on the readme. I would've preferred not spending the time I did debugging and moving on to another solution.

**Comment by rodneyrehm** [comment]
> I'd suggest making that disclaimer on the readme.

You're free to send a PR for that.

**Comment by ooxi** [comment]
I have literally never heard of anybody wanting to use pre minified libraries together with a framework like requriejs.

**Comment by viveleroi** [comment]
I probably shouldn't reply to such a baited, un-helpful statement - but we can use either source or minified, we have a compression system on our deployment chain - we only use minified files from vendor libraries when they exist. 

What you're really saying is "I can't believe someone's using requirejs to load libraries not compressed with r.js" which happens often. *I* have literally never had a library make an assumption as to what optimizer someone's using.

I'm displeased overall with how I'm being replied to so I'm quite happy to have found an alternative.

**Comment by rodneyrehm** [comment]
> I'm displeased overall with how I'm being replied to […]

How would you have liked to be replied to?

You had a problem (minified files do not work with RequireJS) to which the cause was quickly identifed (URI.js "build tool" simply concatenates the scripts without using R.js). There was a work-around suggested (use the source files and optimize on your end), which you did not like. You stated that this should be mentioned in the Readme, which is not an unreasonable request, that was responded with the offer to send a PR.

Nobody was rude to you. Nobody shot your request down as unreasonable. But, yes nobody jumped to fix this problem for you. You're free to participate, to improve the project any way you can and want. This is an open source project with a [history of accepting PRs small and large](https://github.com/medialize/URI.js/pulls?q=is%3Apr+is%3Aclosed).

> […] so I'm quite happy to have found an alternative. 

An option URI.js advertises in the [Readme](https://github.com/medialize/URI.js#alternatives). If the library you chose is not listed there, please send a link.
