### ISSUE TITLE
Inconsistencies with dot-segment normalization

### ISSUE THREAD

**Issue by JordanMilne** [medialize/URI.js#264]
It seems like "%2E%2E" should be treated the same as ".." during dot segment normalization, but it isn't:

```javascript
> URI('/foo/../bar').normalize().toString()
'/bar'
> URI('/foo/%2E%2E/bar').normalize().toString()
'/foo/../bar'
```

Looks like it's because [the normalization of %2E -> . happens after the paths are resolved.](https://github.com/medialize/URI.js/blob/269ceff207237c0b0742dba7101b399f66ff5a5a/src/URI.js#L1872)

Another one:

```javascript
// v correct
> URI('/foo/.bar').normalize().toString()
'/foo/.bar'
// v incorrect
> URI('/foo/..bar').normalize().toString()
'bar'

**Comment by rodneyrehm** [comment]
> It seems like "%2E%2E" should be treated the same as ".." during dot segment normalization, but it isn't:

While [Remove Dot Segments](http://tools.ietf.org/html/rfc3986#section-5.2.4) does not mention percent encoded values at all, it looks like you're right in the `.normalize()` context.

> ```js
 URI('/foo/..bar').normalize().toString()
'bar'
```

this is definitely a bug.

---

Are you up to the task and want to send a PR?

There are a bunch of tests for [`.normalizePath()`](https://github.com/medialize/URI.js/blob/gh-pages/test/test.js#L1095) already.

From today's perspective I'd likely rewrite [`URI.normalizePath()`](https://github.com/medialize/URI.js/blob/269ceff207237c0b0742dba7101b399f66ff5a5a/src/URI.js#L1804) to base on [`URI.segmentCoded()`](https://github.com/medialize/URI.js/blob/269ceff207237c0b0742dba7101b399f66ff5a5a/src/URI.js#L1647) and work on the array of segments, rather than string mutation.

**Comment by JordanMilne** [comment]
>While Remove Dot Segments does not mention percent encoded values at all, it looks like you're right in the .normalize() context.

It's not clear to me from the RFC what order syntax normalizations _should_ be applied in, but it looks like most browsers apply [Percent Encoding Normalization](https://tools.ietf.org/html/rfc3986#section-6.2.2.2) before removing dot segments:

```javascript
> new URL("http://example.com/foo/%2E%2E/bar").pathname
"/bar"
```
> Are you up to the task and want to send a PR?

Sure thing, might take me 'til the weekend though

**Comment by rodneyrehm** [comment]
> Sure thing, might take me 'til the weekend though

no worries, take your time :)
