### ISSUE TITLE
Some questions about expected behaviour.

### ISSUE THREAD

**Issue by dukedougal** [medialize/URI.js#280]
**Case 1: - this is what I expected**
```
    var uri = new URI('/');
    uri.suffix('/rabbits/base/blah.json')
    uri.segment(0, 'us-east-1:1e3ee2dd-4537-4aa2-95d4-fadfd6828388')
    console.log(uri.toString());
```

**Case 1 console output:**
`/us-east-1:1e3ee2dd-4537-4aa2-95d4-fadfd6828388/rabbits/base/blah.json`

**Case 2: why is there a dot in the URL?**
```
    var uri = new URI('/');
    uri.segment(0, 'us-east-1:1e3ee2dd-4537-4aa2-95d4-fadfd6828388')
    uri.suffix('/rabbits/base/blah.json')
    console.log(uri.toString());
```

**Case 2 console output:**
`/us-east-1:1e3ee2dd-4537-4aa2-95d4-fadfd6828388./rabbits/base/blah.json`

**Case 3: is creating a new uri meant to pick up the current page URL?**
```
    var uri = new URI();
    console.log(uri.toString());
```
**Case 3 console output:**
`file:///C:/Users/person/devel/thisfolder/app/hot-dev-app.html#/instances?_k=nijh5b`

**Comment by rodneyrehm** [comment]
It appears you have found a bug in [`.suffix()`](http://medialize.github.io/URI.js/docs.html#accessors-suffix). `suffix()` is meant to target the ".json" part of the path, but you use it to append a path, rather than change the filename's suffix.

Your case 1 and 2 are composing paths, much like you'd do with Node's [`path.join()`](https://nodejs.org/api/path.html#path_path_join_path1_path2). URI.js does not offer a simple way to do that yet, but this could look something like this:

```js
URI.joinPaths = function() {
  var segments = [].reduce.call(arguments, function(previous, current) {
    var _segments = new URI(current).segment();
    return previous.concat(_segments);
  }, []).filter(Boolean);

  return new URI('').segment(segments);
};

URI.joinPaths('/a/b', '/c', 'd', '/e').toString();
// "a/b/c/d/e"
// (should have leading "/")

URI.joinPaths('a/b', 'http://example.com/c', new URI('d/'), '/e').toString();
// "a/b/c/d/e"

URI.joinPaths('a').toString();
// "a"

URI.joinPaths('').toString();
// "/"
// (should be empty string "")

URI.joinPaths('a', '', '', 'b', '', '').toString();
// "a/b"
// (should have trailing "/")
```

Your "case 2" is adding a dot, because `/us-east-1:1e3ee2dd-4537-4aa2-95d4-fadfd6828388` does not have a suffix, so one is appended: `basename "." suffix`.

> Case 3: is creating a new uri meant to pick up the current page URL?

yes, [literally the first example in the docs](http://medialize.github.io/URI.js/docs.html#constructor)

**Comment by dukedougal** [comment]
"""Your case 1 and 2 are composing paths, much like you'd do with Node's path.join(). URI.js does not offer a simple way to do that yet,"""

Ahh yes OK. I spent a long time in the docs trying to work out how to compose a path and there was so much functionality there that I assumed it did it but I just couldn't see how.

**Comment by dukedougal** [comment]
Any chance you might add "compose path" functionality to the system, as you have described above?

thanks

**Comment by rodneyrehm** [comment]
I've opened #285 so that someone can have a look :)
