### ISSUE TITLE
path() & pathname() not decoding correctly

### ISSUE THREAD

**Issue by ezra-quemuel** [medialize/URI.js#305]
When I do the following:
```javascript
const URI = require('urijs');
let uri = new URI('https://somehost/somefolder/file%20name_%231.ext');
uri.path(true);
```
I get **'/somefolder/file name_%231.ext'**, but in this case I'm expecting **'/somefolder/file name_#1.ext'**

After doing a little bit of digging I found that in https://github.com/medialize/URI.js/blob/gh-pages/src/URI.js#L416 it's re-encoding the already decoded **'#'** using a replace function. Shouldn't passing true to **pathname()** decode the whole path?

**Comment by rodneyrehm** [comment]
I see how this might be confusing.

> Shouldn't passing true to pathname() decode the whole path?

The characters `/`, `?` and `#` are not decoded in order to not accidentally change the semantics of

```
/some/ring%2Fding%3Fquery=value%23fragment
```

to

```
/some/ring/ding?query=value#fragment
```

All the other characters can be decoded, because they have no meaning in the context of delimiting path, query and fragment.

If you need everything decoded, have a look at [`.segmentCoded()`](http://medialize.github.io/URI.js/docs.html#accessors-segmentCoded):

```js
URI('/some/ring%2Fding%3Fquery=value%23fragment').segmentCoded();
// ["some", "ring/ding?query=value#fragment"]
```

So with `URI(…).segmentCoded().join('/')` you'll get what you thought `.pathname(true)` would do - a potentially different resource…
