### ISSUE TITLE
Calling absoluteTo on URIs that are already absolute causes error

### ISSUE THREAD

**Issue by MakiCode** [medialize/URI.js#355]
To reproduce, install the library with npm and then create a file with the following lines:

```
var URI = require("urijs");
var google = new URI('http://www.google.com');
google.absoluteTo("http://");
```

Running `node test.js` gives me this error: `TypeError: Hostname cannot be empty, if protocol is http`

**Comment by rodneyrehm** [comment]
hey there!

unfortunately the example makes little sense - what are you trying to achieve?

**Comment by MakiCode** [comment]
Since posting this I've actually discovered that this example from the docs:

```
var u = new URI('//example.com/path');
u.absoluteTo('https://');
```

No longer works and that it's due to this shortcut:

```
    if (!(base instanceof URI)) {
      base = new URI(base);
    }
```

Breaking when there isn't a URI.

Anyway, I discovered this while trying to use this library called CrawlKit on a project, here's the relevant function:

```
    const addUrl = (u) => {
      let url = urijs(u);
      url = url.absoluteTo(defaultAbsoluteTo); //This variable's value is 'http://'
      url.normalize();
      url = url.toString();

      if (!seen.has(url)) {
        logger.info(`Adding ${url}`);
        seen.add(url);
        q.push(new Scope(url));
        logger.info(`${q.length()} task(s) in the queue.`);
      } else {
        logger.debug(`Skipping ${url} - already seen.`);
      }
    };
```
I believe they're trying to clean up the random URLs or domain names or what not that's passed to their library, so just returning the same URL would be good for my use case.

**Comment by rodneyrehm** [comment]
As the hostname validation caused some kerfuffle I've decided to make this feature *opt-in*, thereby returning to the previous default behavior of v1.18.10. As of [v1.19.0](https://github.com/medialize/URI.js/releases/tag/v1.19.0) you can activate hostname validation globally by setting `URI.preventInvalidHostname = true`, or on an instance by calling `.preventInvalidHostname(true)`.

I'm sorry for the confusion, inconvenience caused by the original change and the delayed rectification.

**Comment by MakiCode** [comment]
Thanks for the update!
